<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>test</name>
   <tag></tag>
   <elementGuidId>2d873603-451f-4e2d-9f9e-8b201588ef5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>111${GlobalVariable.G_User_J01}2222</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>111${GlobalVariable.G_User_J01}2222</value>
   </webElementProperties>
</WebElementEntity>
