<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>switch_autoRemaind</name>
   <tag></tag>
   <elementGuidId>0f30ee26-87d9-4758-ba17-37f71fb92c3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MR_自動リマインド&quot;]//div[@role=&quot;switch&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MR_自動リマインド&quot;]//div[@role=&quot;switch&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MeetingLandDepend/iframe/iframe__fullscreen-app-host</value>
   </webElementProperties>
</WebElementEntity>
