<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_LmailSend</name>
   <tag></tag>
   <elementGuidId>c7d22eb0-b44e-44b2-87c9-ac1f2da5b522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MR_送信ボタン_臨場&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MR_送信ボタン_臨場&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
