<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_MeetStop_NO</name>
   <tag></tag>
   <elementGuidId>56f1b893-a92e-4dbb-811d-a65362ccf7ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_開催中止確認_いいえボタン&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_開催中止確認_いいえボタン&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
