<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_taskAdd</name>
   <tag></tag>
   <elementGuidId>93baa901-3a40-4bbc-ba83-057d99dd9c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_議題追加ボタン&quot;]//div[text()=&quot;議題あり&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_議題追加ボタン&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
