<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Msg_mailSendWait</name>
   <tag></tag>
   <elementGuidId>75ed7558-8d22-471d-bb28-68e0d0911437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_招集通知送付待ちへボタン&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_招集通知送付待ちへボタン&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
