<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_MeetStop_No_sendmail</name>
   <tag></tag>
   <elementGuidId>45e383ca-d491-4161-8a32-3ba499862918</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MR_送信ボタン_書面_メール無し&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MR_送信ボタン_書面_メール無し&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
