<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SK_btn_skip</name>
   <tag></tag>
   <elementGuidId>e9ddfd69-41dd-46b4-b82d-00edb0f9f07d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MR_書_送信ボタン_書面決議提案書_メール無し&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MR_書_送信ボタン_書面決議提案書_メール無し&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
