<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SK_btn_book_confirm_proposal_Template</name>
   <tag></tag>
   <elementGuidId>1ec84716-a160-4520-a9f0-b504292b9c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_書FA_書面決議Tmpl作成ボタン&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_書FA_書面決議Tmpl作成ボタン&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
