<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SK_Page_load</name>
   <tag></tag>
   <elementGuidId>5c57a478-3770-4d0a-9952-a86c3aeee0f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;LoadingGif_会議詳細&quot;]//div[@class=&quot;appmagic-image-pseudo-button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;LoadingGif_会議詳細&quot;]//div[@class=&quot;appmagic-image-pseudo-button&quot;]</value>
   </webElementProperties>
</WebElementEntity>
