<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SK_btn_over_sendmail</name>
   <tag></tag>
   <elementGuidId>70b5c500-d869-434e-8961-d199110c2aac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>data-control-name=&quot;MR_送信ボタン_書面&quot;</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>data-control-name=&quot;MR_送信ボタン_書面&quot;</value>
   </webElementProperties>
</WebElementEntity>
