<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SK_btn_noOVer_YES</name>
   <tag></tag>
   <elementGuidId>aab8b4f2-2ea6-4cd3-b633-37a365555a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_M_書_否決完了確認_はいボタン&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_M_書_否決完了確認_はいボタン&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
