<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Msg</name>
   <tag></tag>
   <elementGuidId>70ee2532-b980-42f4-a769-d869d216cb2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;drop-content&quot;]//div[text()=&quot;招集通知&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;drop-content&quot;]//div[text()=&quot;招集通知&quot;]</value>
   </webElementProperties>
</WebElementEntity>
