<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SK_btn_confirm_in_nohave_YES</name>
   <tag></tag>
   <elementGuidId>e5e744b0-e46e-489c-ac2e-43b7b91daa70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_議事録押印無し確認_はいボタン&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_議事録押印無し確認_はいボタン&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
