<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SK_btn_confirm_in_nohave_NO</name>
   <tag></tag>
   <elementGuidId>c636f63c-17c1-4948-b6ad-34eba7826aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_議事録押印無し確認_いいえボタン&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_議事録押印無し確認_いいえボタン&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
