<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>S_agree_have</name>
   <tag></tag>
   <elementGuidId>c8bc0cef-7ba2-4295-8822-92485f30b2b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role=&quot;listbox&quot;]//div[text()=&quot;同意&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role=&quot;listbox&quot;]//div[text()=&quot;同意&quot;]</value>
   </webElementProperties>
</WebElementEntity>
