<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>S_diff_no</name>
   <tag></tag>
   <elementGuidId>dc447494-45d0-4386-a4c4-c949841ccc88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role=&quot;listbox&quot;]//div[text()=&quot;異議なし&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role=&quot;listbox&quot;]//div[text()=&quot;異議なし&quot;]</value>
   </webElementProperties>
</WebElementEntity>
