<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L_btn_continue</name>
   <tag></tag>
   <elementGuidId>f258d895-7355-4746-827d-19403983eb6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MR_MCC_続けるボタン_臨場&quot;]//div[text()=&quot;続ける&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MR_MCC_続けるボタン_臨場&quot;]//div[text()=&quot;続ける&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MeetingLandDepend/iframe/iframe__fullscreen-app-host</value>
   </webElementProperties>
</WebElementEntity>
