<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>S_text_file3</name>
   <tag></tag>
   <elementGuidId>3f3110dc-3cd7-4e4e-aa51-c26cd272a580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_書_役員ギャラリー&quot;]//div[@aria-posinset=&quot;3&quot;]//div[@data-control-name=&quot;MD_書_役員_ファイルDL&quot;]//div[@data-control-part=&quot;text&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_書_役員ギャラリー&quot;]//div[@aria-posinset=&quot;3&quot;]//div[@data-control-name=&quot;MD_書_役員_ファイルDL&quot;]//div[@data-control-part=&quot;text&quot;]</value>
   </webElementProperties>
</WebElementEntity>
