<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>S_btn_task_file_update_NO</name>
   <tag></tag>
   <elementGuidId>591dab41-9f05-40d6-a37b-bcb9b0ef0187</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_M_書_議題資料更新確認_いいえボタン&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_M_書_議題資料更新確認_いいえボタン&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
