<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SK_dropdown_filelist</name>
   <tag></tag>
   <elementGuidId>07746ec9-8d9b-4eca-98b8-2c0d42656740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_書FA_ドロップダウンリスト&quot;]//div[@class=&quot;appmagic-dropdownLabelArrow&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_書FA_ドロップダウンリスト&quot;]//div[@class=&quot;appmagic-dropdownLabelArrow&quot;]</value>
   </webElementProperties>
</WebElementEntity>
