<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SK_file_book_confirm_proposal</name>
   <tag></tag>
   <elementGuidId>dd1a87a3-c10f-47c3-bfa0-86db92e69016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;drop-content&quot;]//div[text()=&quot;書面決議提案書&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;drop-content&quot;]//div[text()=&quot;書面決議提案書&quot;]</value>
   </webElementProperties>
</WebElementEntity>
