<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_time_sort</name>
   <tag></tag>
   <elementGuidId>4d416ff7-9c92-4b0d-a3a8-0d3257a889f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;ML_並び替えドロップ&quot;]//div[@class=&quot;appmagic-dropdownLabelArrow&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;ML_並び替えドロップ&quot;]//div[@class=&quot;appmagic-dropdownLabelArrow&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MeetingList/base_iframe</value>
   </webElementProperties>
</WebElementEntity>
