<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>meetName</name>
   <tag></tag>
   <elementGuidId>29f97fd6-39f8-4381-ae80-ab0901781052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;ML_議題一覧&quot;]//div/span[@title=&quot;${aaa}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;ML_議題一覧&quot;]//div/span[@title=&quot;${aaa}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
