<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__fullscreen-app-host</name>
   <tag></tag>
   <elementGuidId>120242e4-42f7-4ebc-b563-60df786d4c33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fullscreen-app-host</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fullscreen-app-host']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id='fullscreen-app-host']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@id='fullscreen-app-host']</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fullscreen-app-host']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
   </webElementXpaths>
</WebElementEntity>
