<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>K_R2_companyName</name>
   <tag></tag>
   <elementGuidId>195053cd-9a83-4799-baf9-8cf70ddd1476</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_書_株主ギャラリー&quot;]//div[@aria-posinset=&quot;2&quot;]//div[@data-control-name=&quot;MD_AG_ソート番号_4&quot;]//input[@appmagic-control=&quot;MD_AG_ソート番号_4textbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_書_株主ギャラリー&quot;]//div[@aria-posinset=&quot;2&quot;]//div[@data-control-name=&quot;MD_AG_ソート番号_4&quot;]//input[@appmagic-control=&quot;MD_AG_ソート番号_4textbox&quot;]</value>
   </webElementProperties>
</WebElementEntity>
