<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>M_12</name>
   <tag></tag>
   <elementGuidId>1576e145-f2bd-488b-94e8-200257b5ddc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-drop-id=&quot;7&quot;]/*/div[@role=&quot;listbox&quot;]//div[text()=&quot;12&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-drop-id=&quot;7&quot;]/*/div[@role=&quot;listbox&quot;]//div[text()=&quot;12&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MeetingLandDepend/iframe/iframe__fullscreen-app-host</value>
   </webElementProperties>
</WebElementEntity>
