<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>K_btn_sendmail</name>
   <tag></tag>
   <elementGuidId>e0be19c9-4e21-4847-b474-62388c5784c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MR_書_送信ボタン_書面決議提案書&quot;]//button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MR_書_送信ボタン_書面決議提案書&quot;]//button</value>
   </webElementProperties>
</WebElementEntity>
