<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>S_btn_R_upload</name>
   <tag></tag>
   <elementGuidId>d4c4d793-1326-42e1-8211-0f68987012a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-control-name=&quot;MD_書_役員ギャラリー&quot;]//div[@aria-posinset=&quot;${GlobalVariable.G_RowNum}&quot;]//div[text()=&quot;アップロード&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-control-name=&quot;MD_書_役員ギャラリー&quot;]//div[@aria-posinset=&quot;${GlobalVariable.G_RowNum}&quot;]//div[text()=&quot;アップロード&quot;]</value>
   </webElementProperties>
</WebElementEntity>
