<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>S_text_filename</name>
   <tag></tag>
   <elementGuidId>fafb3dab-350c-4fd4-b458-7e8f554f06c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role=&quot;listbox&quot;]//div[text()=&quot;${GlobalVariable.G_FileName}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role=&quot;listbox&quot;]//div[text()=&quot;${GlobalVariable.G_FileName}&quot;]</value>
   </webElementProperties>
</WebElementEntity>
